name: 'Auto Ticket link commenter'
description: 'Comments JIRA ticket link in pull request'
inputs:
  jira-project-url:
    description: 'Link of your project URL'
    required: true
  GITHUB_TOKEN:
    description: 'Add token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'anchor'
  color: 'blue'